#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - cd mbr-app
  - ng build --prod


notifications:
  email:
    on_failure: change
    on_success: change